### PR TITLE
Selfdestruct

### PR DESCRIPTION
**Pull request by dfilaretti**
Adds support for the Selfdestruct operation.

### CODE REVIEW

**Comment by dfilaretti** [comment]
Do not review yet please. 

There's something going on with the test harness. Seems like `log,xml` is malformed. I'm investigating.

**Comment by dwightguth** [comment]
@dfilaretti this is a known issue fixed in my pull request and only happens when tests are already failing. You should investigate the test failures rather than the Jenkins issue.

**Comment by theo25** [comment]
This should not be reviewed/merged yet.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
